USE quiz_system;
INSERT INTO questions (question_text, option1, option2, option3, option4, correct_option, difficulty) VALUES
('What color is the sky on a clear day?', 'Blue', 'Green', 'Red', 'Yellow', 1, 'easy'),
('How many days are in a week?', '5', '6', '7', '8', 3, 'easy'),
('What is the first letter of the English alphabet?', 'A', 'B', 'C', 'D', 1, 'easy'),
('What is 1 + 1?', '1', '2', '3', '4', 2, 'easy'),
('Which animal barks?', 'Cat', 'Dog', 'Cow', 'Fish', 2, 'easy'),
('What do you use to write?', 'Fork', 'Pencil', 'Plate', 'Shoe', 2, 'easy'),
('What shape has three sides?', 'Square', 'Circle', 'Triangle', 'Rectangle', 3, 'easy'),
('How many wheels does a bicycle have?', '1', '2', '3', '4', 2, 'easy'),
('Which is a fruit?', 'Carrot', 'Apple', 'Potato', 'Bread', 2, 'easy'),
('What do bees make?', 'Milk', 'Honey', 'Bread', 'Cheese', 2, 'easy'),
('What sound does a cow make?', 'Meow', 'Bark', 'Moo', 'Chirp', 3, 'easy'),
('What is the opposite of hot?', 'Warm', 'Cold', 'Dry', 'Soft', 2, 'easy'),
('What do you drink from?', 'Table', 'Glass', 'Shoe', 'Book', 2, 'easy'),
('What is 5 - 2?', '1', '2', '3', '4', 3, 'easy'),
('Which season is cold?', 'Summer', 'Winter', 'Spring', 'Autumn', 2, 'easy'),
('Which animal lives in water?', 'Lion', 'Elephant', 'Fish', 'Monkey', 3, 'easy'),
('What do you wear on your feet?', 'Hat', 'Shoes', 'Gloves', 'Scarf', 2, 'easy'),
('How many letters in the word "cat"?', '2', '3', '4', '5', 2, 'easy'),
('Which direction is opposite of left?', 'Right', 'Up', 'Down', 'Forward', 1, 'easy'),
('Which one is a vegetable?', 'Orange', 'Tomato', 'Apple', 'Banana', 2, 'easy'),
('What color are bananas?', 'Blue', 'Green', 'Yellow', 'Red', 3, 'easy'),
('What is 3 + 2?', '4', '5', '6', '7', 2, 'easy'),
('Which animal says "quack"?', 'Dog', 'Duck', 'Cat', 'Cow', 2, 'easy'),
('What tool do you use to cut paper?', 'Spoon', 'Scissors', 'Pencil', 'Eraser', 2, 'easy'),
('What shape is a ball?', 'Square', 'Cylinder', 'Circle', 'Sphere', 4, 'easy'),
('Which part of the body do you use to see?', 'Ear', 'Nose', 'Eye', 'Mouth', 3, 'easy'),
('How many legs does a spider have?', '4', '6', '8', '10', 3, 'easy'),
('Which is a flying animal?', 'Cow', 'Fish', 'Bird', 'Snake', 3, 'easy'),
('What day comes after Monday?', 'Sunday', 'Tuesday', 'Wednesday', 'Thursday', 2, 'easy'),
('What is the color of grass?', 'Purple', 'Green', 'Pink', 'Orange', 2, 'easy'),
('Which sound does a lion make?', 'Roar', 'Tweet', 'Moo', 'Bark', 1, 'easy'),
('What is 10 - 4?', '5', '6', '7', '8', 2, 'medium'),
('Which planet is closest to the sun?', 'Earth', 'Mars', 'Mercury', 'Venus', 3, 'medium'),
('What is the capital of England?', 'Paris', 'London', 'Rome', 'Berlin', 2, 'medium'),
('Which gas do we breathe in to live?', 'Carbon dioxide', 'Nitrogen', 'Oxygen', 'Helium', 3, 'medium'),
('What is 7 x 5?', '30', '35', '40', '45', 2, 'medium'),
('Which organ pumps blood?', 'Lungs', 'Kidney', 'Heart', 'Stomach', 3, 'medium'),
('What temperature does water boil at in Celsius?', '90', '95', '100', '105', 3, 'medium'),
('Who wrote "Hamlet"?', 'Shakespeare', 'Tolstoy', 'Hemingway', 'Austen', 1, 'medium'),
('What is the largest continent?', 'Africa', 'Asia', 'Europe', 'Australia', 2, 'medium'),
('What is 12 / 3?', '3', '4', '5', '6', 2, 'medium'),
('Which is a prime number?', '8', '9', '11', '12', 3, 'medium'),
('What do plants need for photosynthesis?', 'Bread', 'Light', 'Milk', 'Ice', 2, 'medium'),
('What is the chemical symbol for water?', 'H2O', 'CO2', 'O2', 'NaCl', 1, 'medium'),
('How many months are in a year?', '10', '11', '12', '13', 3, 'medium'),
('Which is not a mammal?', 'Whale', 'Dolphin', 'Penguin', 'Tiger', 3, 'medium'),
('What is 15 - 7?', '7', '8', '9', '10', 2, 'medium'),
('What is the freezing point of water in Celsius?', '0', '10', '20', '30', 1, 'medium'),
('Which country is known for the Eiffel Tower?', 'Spain', 'Italy', 'France', 'Germany', 3, 'medium'),
('What is 9 x 3?', '18', '24', '27', '30', 3, 'medium'),
('What is the main language spoken in Brazil?', 'Spanish', 'English', 'Portuguese', 'French', 3, 'medium'),
('Who painted the Mona Lisa?', 'Van Gogh', 'Picasso', 'Da Vinci', 'Rembrandt', 3, 'medium'),
('What is 8 / 2?', '2', '3', '4', '5', 3, 'medium'),
('What planet is known as the Red Planet?', 'Earth', 'Mars', 'Jupiter', 'Saturn', 2, 'medium'),
('What is 6 + 7?', '12', '13', '14', '15', 2, 'medium'),
('Which element is used in light bulbs?', 'Gold', 'Silver', 'Tungsten', 'Iron', 3, 'medium'),
('What is the largest ocean?', 'Atlantic', 'Indian', 'Pacific', 'Arctic', 3, 'medium'),
('Which is the smallest prime number?', '1', '2', '3', '4', 2, 'medium'),
('What is 14 - 5?', '8', '9', '10', '11', 2, 'medium'),
('What is 12 + 8?', '18', '19', '20', '21', 3, 'medium'),
('What is the powerhouse of the cell?', 'Ribosome', 'Nucleus', 'Mitochondria', 'Chloroplast', 3, 'medium'),
('What is 13 x 2?', '24', '25', '26', '27', 3, 'medium'),
('Which is a renewable energy source?', 'Coal', 'Oil', 'Sunlight', 'Gas', 3, 'medium'),
('What is 18 / 3?', '5', '6', '7', '8', 2, 'medium'),
('What is the tallest land animal?', 'Elephant', 'Giraffe', 'Rhino', 'Bear', 2, 'medium'),
('What is 11 + 6?', '16', '17', '18', '19', 2, 'medium'),
('Which gas do plants release?', 'Oxygen', 'Carbon dioxide', 'Helium', 'Nitrogen', 1, 'medium'),
('What is 16 - 9?', '5', '6', '7', '8', 3, 'medium'),
('Which planet has rings?', 'Mars', 'Earth', 'Venus', 'Saturn', 4, 'medium'),
('What is 20 / 4?', '4', '5', '6', '7', 2, 'hard'),
('Who discovered gravity?', 'Newton', 'Einstein', 'Galileo', 'Tesla', 1, 'hard'),
('What is the square root of 81?', '8', '9', '10', '11', 2, 'hard'),
('What is 7 x 7?', '42', '45', '49', '56', 3, 'hard'),
('Which instrument has keys and strings?', 'Violin', 'Piano', 'Drum', 'Flute', 2, 'hard'),
('What is 2 to the power of 5?', '16', '24', '32', '64', 3, 'hard'),
('Which gas is essential for combustion?', 'Oxygen', 'Nitrogen', 'Hydrogen', 'Helium', 1, 'hard'),
('What is 100 divided by 5?', '15', '18', '20', '25', 3, 'hard'),
('What is 11 x 11?', '110', '111', '121', '132', 3, 'hard'),
('What is the capital of Japan?', 'Beijing', 'Dhaka', 'Seoul', 'Tokyo', 4, 'hard'),
('What is 15 + 9?', '22', '23', '24', '25', 3, 'hard'),
('What is the chemical symbol for iron?', 'Fe', 'Ir', 'I', 'In', 1, 'hard'),
('What is 18 - 9?', '8', '9', '10', '11', 2, 'hard'),
('Which planet is farthest from the sun?', 'Neptune', 'Uranus', 'Saturn', 'Pluto', 1, 'hard'),
('What is 25 / 5?', '4', '5', '6', '7', 2, 'hard'),
('What is 14 x 3?', '42', '44', '45', '46', 1, 'hard'),
('What is the largest bone in the human body?', 'Femur', 'Skull', 'Spine', 'Tibia', 1, 'hard'),
('What is 13 + 14?', '26', '27', '28', '29', 3, 'hard'),
('What is the formula for area of a rectangle?', 'l+w', 'l*w', '2l+2w', 'l^2', 2, 'hard'),
('What is 30 - 12?', '16', '17', '18', '19', 3, 'hard'),
('Which is not a prime number?', '13', '17', '21', '19', 3, 'hard'),
('What is 7 squared?', '42', '46', '49', '56', 3, 'hard'),
('What is the capital of Canada?', 'Toronto', 'Vancouver', 'Ottawa', 'Montreal', 3, 'hard'),
('What is 8 x 6?', '42', '44', '48', '50', 3, 'hard'),
('What is the largest planet in our solar system?', 'Earth', 'Jupiter', 'Mars', 'Venus', 2, 'hard'),
('What is 28 / 7?', '3', '4', '5', '6', 2, 'hard'),
('What is the process by which plants make food?', 'Respiration', 'Digestion', 'Photosynthesis', 'Transpiration', 3, 'hard'),
('What is 9 squared?', '72', '81', '90', '99', 2, 'hard'),
('What organ filters blood in the human body?', 'Liver', 'Kidney', 'Lungs', 'Heart', 2, 'hard'),
('What is 17 + 8?', '24', '25', '26', '27', 2, 'hard'),
('What is the symbol for gold?', 'Ag', 'Au', 'Pt', 'Pb', 2, 'hard'),
('What is 36 / 6?', '5', '6', '7', '8', 2, 'hard'),
('Which gas makes up most of Earth’s atmosphere?', 'Oxygen', 'Hydrogen', 'Nitrogen', 'Carbon dioxide', 3, 'hard'),
('What is 21 - 13?', '6', '7', '8', '9', 2, 'hard'),
('What is the chemical formula for table salt?', 'NaCl', 'H2O', 'CO2', 'NH3', 1, 'hard');
